name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    # Cleanup steps to free up disk space
    - name: Cleanup disk space
      if: runner.os == 'Linux'
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        
    - name: Build the Docker image
      run: docker build -t hvgazula/cortexode ./docker
      
    # Cleanup steps to free up disk space

    # Push the Docker image to Docker Hub (only if the PR is merged)
    - name: Push Docker image
#     if: github.event.pull_request.merged == true
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push hvgazula/cortexode
